enableGlobalCache: true

pnpEnableInlining: true

yarnPath: .yarn/releases/yarn.js

pnpMode: "strict"

packageExtensions:
  "@ampproject/toolbox-optimizer@*":
    dependencies:
      "cross-fetch": "*"
      "dom-serializer": "*"
      "postcss": "*"
