enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpEnableInlining: true

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.5.1.cjs
